name: tokemak-challenge
services:
  launcher:
    environment:
      CHALLENGE: tokemak
      FLAG: "rctf{t0k3m4k_p1l0ts_un1t3_!_0855a9744cf49eda7b3ad8b4}"
    container_name: tokemak
    image: tokemak
    build:
      context: .
      target: chroot
    command: socat TCP-LISTEN:1337,reuseaddr,fork exec:"python3 -u challenge/challenge.py"
    expose:
      - 1337
    ports:
      - "1337:1337"
    networks:
      - ctf_network
networks:
  ctf_network:
    name: remedyctf
    external: true
